services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment: 
      PORT: 5080
      PINECONE_HOST: localhost
    ports: 
      - "5080-5090:5080-5090"
    platform: linux/amd64
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  dense-index:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    container_name: dense-index
    environment:
      PORT: 5081
      INDEX_TYPE: serverless
      VECTOR_TYPE: dense
      DIMENSION: 1536
      METRIC: cosine
    ports:
      - "5081:5081"
    platform: linux/amd64
    depends_on:
      pinecone:
        condition: service_healthy

  rag-server:
    build:
      context: .
      dockerfile: src/Dockerfile
    environment:
      - PINECONE_HOST=http://pinecone:5080
      - PINECONE_INDEX_NAME=dense-index
      - APP_RETRIEVER_TOPK=4
    volumes:
      - ./data:/app/data
      - ./tmp-data:/tmp-data
    ports:
      - "8000:8000"
    depends_on:
      pinecone:
        condition: service_healthy 