services:
  # Local Pinecone setup
  pinecone-local:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment: 
      PORT: 5081
      PINECONE_HOST: localhost
    ports: 
      - "5081-5090:5081-5090"
    platform: linux/amd64

networks:
  default:
    name: nvidia-rag 