services:
  pinecone-local:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment: 
      PORT: 5080
      PINECONE_HOST: localhost
    ports: 
      - "5080-5090:5080-5090"
    platform: linux/amd64
    networks:
      - nvidia-rag

    healthcheck:
      test: ["CMD", "curl", "-f", "http://pinecone-local:5080/indexes", "-H", "Api-Key: pclocal", "-H", "X-Pinecone-API-Version: 2025-01"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  nvidia-rag:
    driver: bridge
